services:
  assistant:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - assistant:/app/data
      - assistant:/app/vector_db
      - assistant:/app/sessions
    environment:
      - GIGACHAT_CREDENTIALS=${GIGACHAT_CREDENTIALS}
      - GIGACHAT_SCOPE=${GIGACHAT_SCOPE}
      - TM_PASSWORD=${TM_PASSWORD}       # ← добавьте эту строку
    restart: unless-stopped
volumes:  
  assistant:
